-- AlterTable
ALTER TABLE `DataSpp` ADD COLUMN `acc1Status` ENUM('APPROVED', 'NOT_APPROVED', 'WAITING') NOT NULL DEFAULT 'WAITING',
    ADD COLUMN `acc2Status` ENUM('APPROVED', 'NOT_APPROVED', 'WAITING') NOT NULL DEFAULT 'WAITING',
    ADD COLUMN `accFinalStatus` ENUM('APPROVED', 'NOT_APPROVED', 'WAITING') NOT NULL DEFAULT 'WAITING',
    MODIFY `sppStatus` ENUM('APPROVED', 'NOT_APPROVED', 'WAITING') NOT NULL DEFAULT 'WAITING';
